# Generated by Django 5.2.5 on 2025-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, default=0, null=True)),
                ("genre", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
