# Generated by Django 5.2.5 on 2025-09-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="movies/"),
        ),
    ]
