# Generated by Django 5.2.5 on 2025-09-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_movie_description_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
