# Generated by Django 5.2.5 on 2025-09-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_movie_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("image", models.CharField(blank=True, max_length=300, null=True)),
                ("cuisine", models.CharField(max_length=100)),
            ],
        ),
    ]
