# Generated by Django 5.2.5 on 2025-09-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_food"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="cuisine",
        ),
    ]
