# Generated by Django 5.2.5 on 2025-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_food_cuisine"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, default=0, null=True)),
                ("role", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
