# Generated by Django 5.2.5 on 2025-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_teammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
