# Generated by Django 5.2.6 on 2025-11-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
    ]
